--- #YAML:1.0
name:               Gtk2-Ex-NumAxis
version:            3
abstract:           Widget drawing a numbered axis.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Glib::Ex::SignalBits:  9
    Glib::Ex::SignalIds:  1
    Glib::Object::Subclass:  0
    Gtk2:                 1.220
    Math::Round:          0
    perl:                 5.008
resources:
    homepage:  http://user42.tuxfamily.org/gtk2-ex-numaxis/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
        - examples
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            Pod::Simple::HTML:  0
            warnings::unused:   0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            Test::Weaken:        3
            Test::Weaken::Gtk2:  0
